### PR TITLE
Introduce deobjectidify.awk for removing unwanted ObjectIDs

### PR DESCRIPTION
**Pull request by busstoptaktik**
deobjectidify.awk removes unwanted ObjectIDs from the database dump files.

Syntax:

    awk -f deobjectidify.awk WHATEVER.sql | sqlplus -s USER/PASSWORD@BLABLA

### CODE REVIEW

**Comment by AsgerPetersen** [comment]
Well, we still have some issues with loading data this way. Tracked in /Septima/fikspunktsregister#47

**Comment by bjornharrtell** [comment]
The script is effective but sensitive to awk implementation. Seems to be working with GNU awk though and we can make sure we have that installed.

**Comment by bjornharrtell** [comment]
Unfortunately there are other, unrelated, issues (https://github.com/Kortforsyningen/FIRE-DDL/issues/24) hindering progress.

**Comment by busstoptaktik** [comment]
@bjornharrtell do you have any idea what the problem with the script is accroding to mawk's point of view? As far as I can see, I use only nawk constructs, no GNU extensions. But perhaps mawk does not fully support the nawk ("new awk", 1977 style) language?

**Comment by bjornharrtell** [comment]
@busstoptaktik awk is not my primary language and I can't see any obvious that could explain it. But perhaps this passage is relevant (from https://invisible-island.net/mawk/manpage/mawk.html#h2-COMPATIBILITY-ISSUES):

```
       POSIX AWK is oriented to operate on files a line at a time.  RS can  be
       changed  from  "\n" to another single character, but it is hard to find
       any use for this -- there are no examples in the AWK book.  By  conven-
       tion, RS = "", makes one or more blank lines separate records, allowing
       multi-line records.  When RS = "", "\n" is  always  a  field  separator
       regardless of the value in FS.

       mawk,  on  the  other hand, allows RS to be a regular expression.  When
       "\n" appears in records, it is treated as space, and FS  always  deter-
       mines fields.
```

**Comment by busstoptaktik** [comment]
@AsgerPetersen, @bjornharrtell : We agree that the remaining import blues has its roots elsewhere, so you're OK with this being merged?

**Pull request merged**
